// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCBgN3_SRd6rgcBnN3mIss67Q14aQl0w',
    appId: '1:550349653767:web:21305d829533edc52b67a2',
    messagingSenderId: '550349653767',
    projectId: 'flutternotilocalandremote',
    authDomain: 'flutternotilocalandremote.firebaseapp.com',
    storageBucket: 'flutternotilocalandremote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Z6rswtD5BlX-paVOIJKo_58zHQFXPCg',
    appId: '1:550349653767:android:47e2ec0bfd3dff7a2b67a2',
    messagingSenderId: '550349653767',
    projectId: 'flutternotilocalandremote',
    storageBucket: 'flutternotilocalandremote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyDqjtTOdMRNnJTXsCRRwqwEwJfBErybE',
    appId: '1:550349653767:ios:848737a72e7d46122b67a2',
    messagingSenderId: '550349653767',
    projectId: 'flutternotilocalandremote',
    storageBucket: 'flutternotilocalandremote.appspot.com',
    iosBundleId: 'com.example.flutterNotificationLocalandremote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyDqjtTOdMRNnJTXsCRRwqwEwJfBErybE',
    appId: '1:550349653767:ios:5f187eb2dd9587552b67a2',
    messagingSenderId: '550349653767',
    projectId: 'flutternotilocalandremote',
    storageBucket: 'flutternotilocalandremote.appspot.com',
    iosBundleId: 'com.example.flutterNotificationLocalandremote.RunnerTests',
  );
}
